apiVersion: config.openservicemesh.io/v1alpha1
kind: MeshConfig
metadata:
  name: osm-mesh-config
spec:
  sidecar:
    enablePrivilegedInitContainer: false
    logLevel: error
    maxDataPlaneConnections: 0
    envoyImage: "envoyproxy/envoy-alpine:v1.19.1"
    initContainerImage: "openservicemesh/init:v0.9.2"
    configResyncInterval: "0s"
  traffic:
    enableEgress: true
    useHTTPSIngress: true
    enablePermissiveTrafficPolicyMode: true
  observability:
    enableDebugServer: true
    tracing:
      enable: false
