kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: marblerun-traffic-target
  namespace: marblerun
spec:
  destination:
    kind: ServiceAccount
    name: marblerun
    namespace: marblerun-coordinator
  rules:
  - kind: TCPRoute
    name: marble-activation
  sources:
  - kind: ServiceAccount
    name: bookbuyer
  - kind: ServiceAccount
    name: bookthief
  - kind: ServiceAccount
    name: bookstore
  - kind: ServiceAccount
    name: bookwarehouse
---
apiVersion: specs.smi-spec.io/v1alpha4
kind: TCPRoute
metadata:
  name: marble-activation
  namespace: marblerun
spec:
  matches:
    ports:
    - 2001
