kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: marblerun-traffic-target
  namespace: marblerun
spec:
  destination:
    kind: ServiceAccount
    name: marblerun-coordinator
    namespace: marblerun
  rules:
  - kind: TCPRoute
    name: marble-activation
  sources:
  - kind: ServiceAccount
    name: bookbuyer
    namespace: bookbuyer
  - kind: ServiceAccount
    name: bookthief
    namespace: bookthief
  - kind: ServiceAccount
    name: bookstore
    namespace: bookstore
  - kind: ServiceAccount
    name: bookstore-v2
    namespace: bookstore
  - kind: ServiceAccount
    name: bookwarehouse
    namespace: bookwarehouse
---
apiVersion: specs.smi-spec.io/v1alpha4
kind: TCPRoute
metadata:
  name: marble-activation
  namespace: marblerun
spec:
  matches:
    ports: []
